### PR TITLE
Fixed stories

### LINKED ISSUE #50: Fix broken stories
Some of the stories for Storybook are broken after introduction of TypeScript.

### PR DESCRIPTION
**Pull request by NicolajNiels1**
Fixes #50 

The Storybook should be cleaned up though 🤣

### CODE REVIEW

File: src/components/atoms/RecurringTransactionOptions.tsx [hunk 1]
```diff
@@ -1,14 +1,16 @@
-import React from 'react';
+import React, { Dispatch, SetStateAction } from 'react';
 
 import Input from './Input';
 import Select from './Select';
 
+export type intervalType = 'month' | 'week';
```
Comment (FredrikAugust) [inline src/components/atoms/RecurringTransactionOptions.tsx]: Custom types should have a capital first character.

File: src/stories/index.stories.tsx [hunk 2]
```diff
@@ -101,22 +103,61 @@ storiesOf('Dashboard', module)
...
-
-// storiesOf('Transactions', module)
-//   .addDecorator(fn => (
-//   <div style={{ width: '80vw', margin: '2em', background: theme.palette.primary.main }}>
-//   {fn()}
-//   </div>
-//   ))
-//   .add('Transaction page', () => <Transactions />)
-//   .add('Recurring options', () => <RecurringTransactionOptions/>);
+const expenseTx = {
```
Comment (FredrikAugust) [inline src/stories/index.stories.tsx]: Consider using the generator we created, and rather overwrite parameters if you need to set them explicitly. This would make the code a bit DRYer.

File: src/stories/index.stories.tsx [hunk 3]
```diff
@@ -152,41 +193,87 @@ storiesOf('Input/Date', module)
...
+    </div>
+  ))
+  .add('With placeholder', () => {
+    const [value, setState] = React.useState('');
+    return (
+      <TextArea
+        id="_"
+        value={value}
+        setState={setState}
+        placeholder="Insert a funny otter fact."
```
Comment (FredrikAugust) [inline src/stories/index.stories.tsx]: Otters are the best.

File: tslint.json [hunk 4]
```diff
@@ -16,7 +16,8 @@
     "array-type": [true, "generic"],
     "interface-name": [true, "always-prefix"],
     "arrow-return-shorthand": true,
-    "arrow-parens": false
+    "arrow-parens": false,
```
Comment (FredrikAugust) [inline tslint.json]: What is this?

File: src/components/atoms/RecurringTransactionOptions.tsx [hunk 5]
```diff
@@ -45,7 +47,7 @@ const RecurringTransactionOptions: React.FC<IProps> = props => {
         id="intervalType"
         values={selectOptions}
         value={props.intervalTypeValue}
-        setState={props.setTypeInterval}
+        setState={props.setTypeInterval as Dispatch<SetStateAction<string>>}
```
[the remark this answers is not in the document]
Comment (NicolajNiels1) [reply src/components/atoms/RecurringTransactionOptions.tsx]: The Select component takes a React.Dispatch<React.SetStateAction<string>> so TypeScript complains if not.

File: src/components/atoms/RecurringTransactionOptions.tsx [hunk 6]
```diff
@@ -1,14 +1,16 @@
...
+export type intervalType = 'month' | 'week';
+
 interface IProps {
   intervalValue: number;
   setInterval: React.Dispatch<React.SetStateAction<number>>;
-  intervalTypeValue: string;
+  intervalTypeValue: intervalType;
   DoMValue: number;
-  setTypeInterval: React.Dispatch<React.SetStateAction<string>>;
+  setTypeInterval: React.Dispatch<React.SetStateAction<intervalType>>;
```
[the remark this answers is not in the document]
Comment (NicolajNiels1) [reply src/components/atoms/RecurringTransactionOptions.tsx]: Goood catch. Auto-import gotcha! 😮

File: src/stories/index.stories.tsx (hunk 2 above)
Comment (NicolajNiels1) [reply src/stories/index.stories.tsx]: I figured this is just Storybook, and it looks like 💩 	already.

File: tslint.json (hunk 4 above)
Comment (NicolajNiels1) [reply tslint.json]: It is a rule that allows:
```ts
e => someFuntionsBody;
```

and don't require parantheses like this:
```ts
(e) => someFunctionBody;
```

File: src/components/atoms/RecurringTransactionOptions.tsx (hunk 1 above)
Comment (NicolajNiels1) [reply src/components/atoms/RecurringTransactionOptions.tsx]: fixed 😃 Good catch!
